"""
Response Builder for JKYog WhatsApp Bot
Rohan Kothapalli - Week 3 Assignment

Orchestrates bot responses by routing to appropriate handlers based on intent
and integrating with all teammate modules (knowledge base, database, integrations).
Responses are generated by an LLM (Gemini or Grok) using knowledge base content
as context, with hardcoded fallbacks when the LLM is unavailable.
"""

import os
import json
import re
import logging
from typing import Dict, Optional

from .intent_classifier import classify_intent
from .entity_extractor import extract_entities

try:
    from google import genai
    from google.genai import types as genai_types
    _GOOGLE_AVAILABLE = True
except ImportError:
    _GOOGLE_AVAILABLE = False

try:
    import httpx
    _HTTPX_AVAILABLE = True
except ImportError:
    _HTTPX_AVAILABLE = False

try:
    from ..knowledge_base.ingestion import search_kb
except ImportError:
    print("Warning: knowledge_base module not found")
    def search_kb(query, top_k=3):
        return []

try:
    from ..integrations.google_maps import get_temple_directions_from_user_location
except ImportError:
    print("Warning: google_maps integration not found")
    def get_temple_directions_from_user_location(user_location, temple_address, mode="driving"):
        return f"Directions from {user_location} to {temple_address} (integration unavailable)"

try:
    from ..service_wrappers.maps_wrapper import MapsWrapper
except ImportError:
    MapsWrapper = None
    print("Warning: MapsWrapper not found (service_wrappers/maps_wrapper.py)")

try:
    from ..integrations.stripe import get_donation_link
except ImportError:
    print("Warning: stripe integration not found")
    def get_donation_link(temple_slug=None):
        return "https://buy.stripe.com/test_default"

try:
    from ..integrations.calendar import get_upcoming_events, get_events_on_date
except ImportError:
    print("Warning: calendar integration not found")
    def get_upcoming_events(limit=5):
        return []
    def get_events_on_date(date_str):
        return []

try:
    from ..service_wrappers.calendar_wrapper import CalendarWrapper
except ImportError:
    CalendarWrapper = None
    print("Warning: CalendarWrapper not found (service_wrappers/calendar_wrapper.py)")

try:
    from ..service_wrappers.base_wrapper import CircuitBreakerOpenError
except ImportError:
    CircuitBreakerOpenError = None


TEMPLE_ADDRESS = "1450 North Watters Road, Allen, TX 75013"
TEMPLE_NAME = "JKYog Radha Krishna Temple"

logger = logging.getLogger(__name__)

_UNIFIED_SYSTEM_PROMPT = """You are the warm, spiritually uplifting WhatsApp assistant for JKYog Radha Krishna Temple in Allen, Texas.

Analyze the User Message and provided Context, then respond ONLY with a valid JSON object in this exact format (no explanation, no markdown, no code fences):
{"intent": "<intent>", "confidence": <float 0.0-1.0>, "reply_text": "<string>", "next_action": "<string or null>"}

Intent values: greeting | faq_query | event_query | donation_request | directions_request | unknown

Content rules:
- Variety: Never start with the same opening phrase twice in a row. Rotate respectful greetings: "Namaste", "Radhe Radhe", "Hari Om", "It is a joy to assist you", "Blessings to you", "Jai Shri Krishna".
- Context Integration: Weave facts (address, event times, donation link) naturally into warm sentences. Do not just list raw data.
- Recovery Menu: If confidence < 0.7 OR intent is unknown, set reply_text to a graceful recovery menu. Example: "I'm not quite sure I caught that. 🙏 Would you like to hear about:\n• Upcoming Events\n• Temple Directions\n• Donation Information\n• Temple Hours & Info\n\nOr type Menu."
- Tone: Concise, mobile-friendly, under 250 words. Use only simple bullet points with •. No bold text or markdown headers.
- Honesty: If Context does not contain the answer, direct the user to jkyog.org or (469) 606-3119. Never mention AI or knowledge bases."""

_BOT_SYSTEM_PROMPT = """You are the warm, spiritually uplifting WhatsApp assistant for JKYog Radha Krishna Temple in Allen, Texas.

Response Guidelines:
- Variety over Repetition: Never start messages with the same phrase. Rotate respectful greetings: "Namaste", "Radhe Radhe", "Hari Om", "It is a joy to assist you".
- Context Integration: Weave facts (address, event times, donation link) naturally into warm sentences rather than just listing them.
- Fallback Grace: If the intent is unclear, offer a graceful Recovery Menu with bullet options rather than a generic "I don't know."
- Honesty: If Context does not contain the answer, direct the user to jkyog.org or call (469) 606-3119.

Formatting:
- Keep responses under 250 words and optimized for mobile screens.
- Use only simple bullet points with •. No bold text or markdown headers.
- Never mention AI, knowledge bases, or the underlying technology."""


def _generate_with_gemini(user_message: str, context: str) -> str | None:
    """
    Generate a conversational response using Gemini with the given context.
    Legacy path used when single-call is disabled or fails.
    Returns None if Gemini is unavailable or errors.
    """
    if not _GOOGLE_AVAILABLE or not os.getenv("GOOGLE_API_KEY"):
        return None
    try:
        client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))
        prompt = f"Context:\n{context}\n\nUser message: {user_message}"
        response = client.models.generate_content(
            model=os.getenv("GEMINI_MODEL_RESPONSE", "gemini-2.5-flash"),
            contents=prompt,
            config=genai_types.GenerateContentConfig(
                system_instruction=_BOT_SYSTEM_PROMPT,
                temperature=0.4,
                max_output_tokens=600,
            ),
        )
        return response.text.strip()
    except Exception as exc:
        logger.warning("Gemini response generation error: %s", exc)
        return None


def _build_mixed_context(user_message: str) -> str:
    """
    Build a rich context block for the unified single-call path.
    Combines top KB matches (FAQs + events) with static temple info and donation link
    so Gemini can choose the best answer in one call.
    """
    parts: list[str] = []

    results = search_kb(user_message, top_k=5)
    faq_parts: list[str] = []
    event_parts: list[str] = []
    for r in results:
        if r["type"] == "faq" and len(faq_parts) < 2:
            faq = r["payload"]
            faq_parts.append(f"Q: {faq.get('question', '')}\nA: {faq.get('answer', '')}")
        elif r["type"] == "event" and len(event_parts) < 2:
            e = r["payload"]
            event_line = f"Event: {e.get('title', '')}"
            if e.get("day"):
                event_line += f" | When: {e['day']}"
                if e.get("start_time"):
                    event_line += f" at {e['start_time']}"
            event_parts.append(event_line)

    if faq_parts:
        parts.append("FAQs:\n" + "\n\n".join(faq_parts))
    if event_parts:
        parts.append("Events:\n" + "\n".join(event_parts))

    parts.append(
        f"Temple: {TEMPLE_NAME}\n"
        f"Address: {TEMPLE_ADDRESS}\n"
        "Phone: (469) 606-3119\n"
        "Website: jkyog.org"
    )

    try:
        donation_link = get_donation_link(temple_slug="dallas")
        parts.append(f"Donation link: {donation_link}")
    except Exception:
        pass

    return "\n\n---\n\n".join(parts)


def _single_call_gemini(user_message: str, context: str) -> dict | None:
    """
    Single Gemini call that classifies intent and generates the reply together.
    Returns {"intent": str, "confidence": float, "reply_text": str, "next_action": str|None}
    or None on any failure so the caller can fall back to the legacy pipeline.
    """
    if not _GOOGLE_AVAILABLE or not os.getenv("GOOGLE_API_KEY"):
        return None
    try:
        client = genai.Client(api_key=os.getenv("GOOGLE_API_KEY"))
        prompt = f"Context:\n{context}\n\nUser message: {user_message}"
        response = client.models.generate_content(
            model=os.getenv("GEMINI_MODEL_RESPONSE", "gemini-2.5-flash"),
            contents=prompt,
            config=genai_types.GenerateContentConfig(
                system_instruction=_UNIFIED_SYSTEM_PROMPT,
                temperature=0.4,
                max_output_tokens=700,
            ),
        )
        raw = response.text.strip()
        # Strip markdown code fences the model may add despite instructions
        raw = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw, flags=re.MULTILINE).strip()
        result = json.loads(raw)
        return {
            "intent": result.get("intent", "unknown"),
            "confidence": float(result.get("confidence", 0.0)),
            "reply_text": (result.get("reply_text") or "").strip(),
            "next_action": result.get("next_action"),
        }
    except Exception as exc:
        logger.warning("Single-call Gemini failed, falling back to legacy: %s", exc)
        return None


def _generate_with_grok(user_message: str, context: str) -> str | None:
    """
    Generate a conversational response using xAI Grok via the /v1/responses endpoint.
    Returns None if unavailable or errors.

    Endpoint: https://api.x.ai/v1/responses
    Ref: https://docs.x.ai/developers/quickstart
    """
    if not _HTTPX_AVAILABLE:
        return None

    api_key = os.getenv("XAI_API_KEY")
    if not api_key:
        return None

    base_url = os.getenv("XAI_BASE_URL", "https://api.x.ai/v1/responses").strip()
    model = os.getenv("XAI_MODEL", "grok-3-mini").strip()
    timeout_s = float(os.getenv("LLM_TIMEOUT_S", "15"))

    prompt = f"Context:\n{context}\n\nUser message: {user_message}"

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": model,
        "input": [
            {"role": "system", "content": _BOT_SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.4,
    }

    try:
        with httpx.Client(timeout=timeout_s) as client:
            r = client.post(base_url, headers=headers, json=payload)
            r.raise_for_status()
            data = r.json()
        return (data.get("output_text", "") or "").strip() or None
    except Exception as exc:
        print(f"Grok response generation error: {exc}")
        return None


def _generate_with_llm(user_message: str, context: str) -> str | None:
    """
    Provider switch for response generation.

    Env:
      - LLM_PROVIDER: 'gemini' (default) or 'grok'
    """
    provider = (os.getenv("LLM_PROVIDER", "gemini") or "gemini").strip().lower()
    if provider == "grok":
        return _generate_with_grok(user_message, context)
    return _generate_with_gemini(user_message, context)


def _strip_html(html: str) -> str:
    # Google Directions step instructions include HTML tags.
    return re.sub(r"<[^>]+>", "", html or "")


def _get_directions_text_from_maps_wrapper(user_location: str) -> str:
    """
    Primary directions path:
      user_location -> MapsWrapper().directions(...) -> format into directions_text.
    """
    if not MapsWrapper:
        return ""

    try:
        print("calling MapsWrapper.directions (render log)")
        logger.info("calling MapsWrapper.directions | origin=%s", user_location)

        wrapper = MapsWrapper()
        directions_result = wrapper.directions(
            origin=user_location,
            destination=TEMPLE_ADDRESS,
            mode="driving",
        )

        routes = directions_result.get("routes") or []
        if not routes:
            return "❌ Could not find directions for that route."

        legs = routes[0].get("legs") or []
        if not legs:
            return "❌ Could not find directions for that route."

        leg0 = legs[0]
        steps = leg0.get("steps") or []
        total_distance = (leg0.get("distance") or {}).get("text", "") or ""
        total_duration = (leg0.get("duration") or {}).get("text", "") or ""

        lines = []
        if total_distance or total_duration:
            lines.append(f"🗺️ {total_distance} • {total_duration}".strip())

        for idx, step in enumerate(steps, start=1):
            instruction = _strip_html(step.get("html_instructions", "") or "")
            distance = (step.get("distance") or {}).get("text", "") or ""
            if instruction and distance:
                lines.append(f"{idx}. {instruction} ({distance})")
            elif instruction:
                lines.append(f"{idx}. {instruction}")

        return "\n".join(lines).strip() or "❌ Could not find directions for that route."
    except CircuitBreakerOpenError:
        logger.warning("MapsWrapper directions circuit breaker open")
        return ""
    except Exception as exc:
        logger.exception("MapsWrapper directions failed")
        return ""


def _date_part(iso_or_datetime_str: str) -> str:
    """
    Extract 'YYYY-MM-DD' from Google Calendar start values:
      - 'YYYY-MM-DD' (all-day)
      - 'YYYY-MM-DDTHH:MM:SS...' (dateTime)
    """
    if not iso_or_datetime_str:
        return ""
    if len(iso_or_datetime_str) >= 10:
        return iso_or_datetime_str[:10]
    return ""


def _get_calendar_events_from_wrapper(date_str: Optional[str]) -> list[Dict]:
    """
    Primary events path:
      CalendarWrapper().list_events(max_results=20) -> simplify -> optional date filter.
    """
    if not CalendarWrapper:
        return []

    try:
        print("calling CalendarWrapper.list_events (render log)")
        logger.info("calling CalendarWrapper.list_events | date_filter=%s", date_str)

        wrapper = CalendarWrapper()
        calendar_result = wrapper.list_events(max_results=20)
        raw_events = calendar_result.get("events") or []

        simplified: list[Dict] = []
        for item in raw_events:
            summary = item.get("summary") or "Event"
            start_obj = item.get("start") or {}
            start_val = start_obj.get("dateTime") or start_obj.get("date") or ""
            simplified.append({"summary": summary, "start": start_val})

        # If a date was requested, filter by matching the date part of start.
        if date_str:
            simplified = [
                e for e in simplified
                if _date_part(e.get("start", "")).strip() == date_str
            ]

        # WhatsApp-friendly output: only show the most relevant few.
        if not date_str:
            simplified = simplified[:5]

        return simplified
    except CircuitBreakerOpenError:
        logger.warning("CalendarWrapper list_events circuit breaker open")
        return []
    except Exception as exc:
        logger.exception("CalendarWrapper list_events failed")
        return []


def handle_greeting(user_context: Optional[Dict] = None) -> str:
    context = (
        "The user is greeting the bot. Welcome them warmly and briefly list what the bot can help with: "
        "temple information (location, hours, dress code), event schedules (satsang, bhajans, special events), "
        "directions to the temple, and donation information."
    )
    generated = _generate_with_llm("Hello", context)
    if generated:
        return generated

    greeting = "Namaste! Welcome to JKYog Radha Krishna Temple.\n\n"
    greeting += "I can help you with:\n"
    greeting += "• Temple information (location, hours, dress code)\n"
    greeting += "• Event schedules (satsang, bhajans, special events)\n"
    greeting += "• Directions to the temple\n"
    greeting += "• Donation information\n\n"
    greeting += "How can I assist you today?"
    return greeting


def handle_faq_query(user_message: str, entities: Dict) -> str:
    results = search_kb(user_message, top_k=3)

    if results:
        context_parts = []
        for r in results:
            if r["type"] == "faq":
                faq = r["payload"]
                context_parts.append(
                    f"Q: {faq.get('question', '')}\nA: {faq.get('answer', '')}"
                )
        if context_parts:
            context = "\n\n".join(context_parts)
            generated = _generate_with_llm(user_message, context)
            if generated:
                return generated

        # Fallback: return the raw top answer
        top = results[0]
        if top["type"] == "faq":
            faq = top["payload"]
            response = f"{faq.get('answer', '')}\n\n"
            if len(results) > 1:
                response += "Related:\n"
                for r in results[1:3]:
                    if r["type"] == "faq":
                        response += f"• {r['payload'].get('question', '')}\n"
            return response

    return (
        "I don't have specific information about that. "
        "Please contact the temple directly at (469) 606-3119 or visit jkyog.org."
    )


def handle_event_query(user_message: str, entities: Dict) -> str:
    results = search_kb(user_message, top_k=3)
    event_results = [r for r in results if r["type"] == "event"]

    if event_results:
        context_parts = []
        for r in event_results:
            e = r["payload"]
            parts = [f"Event: {e.get('title', '')}"]
            if e.get("description"):
                parts.append(f"Description: {e['description']}")
            if e.get("day"):
                timing = e["day"]
                if e.get("start_time"):
                    timing += f" at {e['start_time']}"
                if e.get("end_time"):
                    timing += f" - {e['end_time']}"
                parts.append(f"When: {timing}")
            if e.get("start_day"):
                parts.append(f"Dates: {e['start_day']} to {e.get('end_day', '')}")
            if e.get("location"):
                parts.append(f"Location: {e['location']}")
            context_parts.append("\n".join(parts))

        context = "\n\n".join(context_parts)
        generated = _generate_with_llm(user_message, context)
        if generated:
            return generated

        # Fallback: format event list
        response = "Events:\n\n"
        for r in event_results[:3]:
            e = r["payload"]
            response += f"• {e.get('title', 'Event')}\n"
            if e.get("day"):
                response += f"  {e['day']}"
                if e.get("start_time"):
                    response += f" at {e['start_time']}"
                response += "\n"
        return response

    # Try calendar integration (primary via CalendarWrapper)
    date_filter = entities.get("date") if isinstance(entities, dict) else None
    calendar_events = _get_calendar_events_from_wrapper(date_filter)

    # Robust fallback: if wrapper fails/unavailable, use legacy integration.
    if not calendar_events:
        calendar_events = (
            get_events_on_date(entities["date"])
            if "date" in entities
            else get_upcoming_events(limit=5)
        )
    if calendar_events:
        response = "Upcoming Events:\n\n"
        for event in calendar_events[:3]:
            response += f"• {event.get('summary', 'Event')}\n"
            response += f"  {event.get('start', '')}\n"
        return response

    return (
        "I couldn't find specific event information. "
        "Please check our website at jkyog.org or call (469) 606-3119."
    )


def handle_donation(entities: Dict) -> str:
    donation_link = get_donation_link(temple_slug="dallas")
    context = (
        f"The user wants to donate to JKYog Radha Krishna Temple. "
        f"The donation link is: {donation_link}. "
        f"Donations are tax-deductible and support temple facilities, spiritual programs, and community service."
    )
    generated = _generate_with_llm("How do I donate?", context)
    if generated:
        return generated

    response = "Thank you for your generous support!\n\n"
    response += f"You can make a donation here:\n{donation_link}\n\n"
    response += "Your contributions help us:\n"
    response += "• Maintain the temple facilities\n"
    response += "• Organize spiritual programs\n"
    response += "• Serve the community\n\n"
    response += "All donations are tax-deductible."
    return response


def handle_directions(user_message: str, entities: Dict) -> str:
    user_location = entities.get("location")
    directions_text = ""

    if user_location:
        # Primary path: service wrapper.
        directions_text = _get_directions_text_from_maps_wrapper(user_location)

        # Robust fallback: if wrapper fails/unavailable, keep old integration.
        if not directions_text:
            directions_text = get_temple_directions_from_user_location(
                user_location=user_location,
                temple_address=TEMPLE_ADDRESS,
            )

    context = (
        f"The user is asking for directions to {TEMPLE_NAME}. "
        f"The address is: {TEMPLE_ADDRESS}. "
        f"Parking is available on-site."
    )
    if directions_text:
        context += f"\n\nDirections details: {directions_text}"

    generated = _generate_with_llm(user_message, context)
    if generated:
        return generated

    response = f"Directions to {TEMPLE_NAME}:\n\n"
    response += f"Address: {TEMPLE_ADDRESS}\n\n"
    if directions_text:
        response += directions_text
    else:
        response += "The temple is located in Allen, Texas.\n\n"
        response += "Use the address above in your GPS for turn-by-turn directions.\n\n"
        response += "Ample parking is available on-site."
    return response


def handle_unknown(user_message: str) -> str:
    context = (
        "The user sent a message the bot doesn't understand or that is outside the scope of temple assistance. "
        "Politely let them know what the bot can help with: temple information, events, directions, and donations. "
        "Provide the temple contact number (469) 606-3119 and website jkyog.org for other inquiries."
    )
    generated = _generate_with_llm(user_message, context)
    if generated:
        return generated

    response = "I'm not sure I understood that.\n\n"
    response += "I can help you with:\n"
    response += "• Temple information (location, hours, facilities)\n"
    response += "• Event schedules and timings\n"
    response += "• Directions to the temple\n"
    response += "• Donation information\n\n"
    response += "For other inquiries, please contact:\n"
    response += "(469) 606-3119\n"
    response += "jkyog.org"
    return response


def build_response(
    user_message: str,
    user_context: Optional[Dict] = None,
    intent: Optional[str] = None,
    confidence: Optional[float] = None,
) -> str:
    """
    Build complete bot response.

    Pipeline (when Gemini is available):
    1. Build mixed context (top KB matches + static temple info + donation link).
    2. Single Gemini call → intent + confidence + reply_text in one shot.
    3. If directions intent + user has a location → enrich reply with live Maps data.
    4. Falls back to legacy classify + handler pipeline if single call fails.
    5. Falls back to hardcoded strings if Gemini is unavailable.

    Set env DISABLE_SINGLE_CALL=1 to force the legacy pipeline.
    """
    if not user_message or not user_message.strip():
        return handle_unknown(user_message)

    try:
        use_single_call = (
            _GOOGLE_AVAILABLE
            and os.getenv("GOOGLE_API_KEY")
            and os.getenv("DISABLE_SINGLE_CALL", "0") not in {"1", "true", "True", "yes"}
        )

        if use_single_call:
            mixed_context = _build_mixed_context(user_message)
            single = _single_call_gemini(user_message, mixed_context)

            if single and single.get("reply_text"):
                detected_intent = single["intent"]
                detected_confidence = single["confidence"]
                reply = single["reply_text"]

                logger.info(
                    "single_call | intent=%s | confidence=%.2f | next_action=%s",
                    detected_intent,
                    detected_confidence,
                    single.get("next_action"),
                )

                # Enrich directions with live Maps data when user provided a location
                if detected_intent == "directions_request":
                    entities = extract_entities(user_message, detected_intent)
                    user_location = entities.get("location")
                    if user_location:
                        directions_text = _get_directions_text_from_maps_wrapper(user_location)
                        if directions_text and "❌" not in directions_text:
                            reply = (
                                f"Radhe Radhe! Here are your driving directions to {TEMPLE_NAME}:\n\n"
                                f"{directions_text}\n\n"
                                f"Address: {TEMPLE_ADDRESS}\n"
                                "Ample parking is available on-site. 🙏"
                            )

                return reply

        # --- Legacy fallback path ---
        if intent is None:
            intent_result = classify_intent(user_message)
            intent = intent_result["intent"]
            confidence = intent_result["confidence"]

        confidence = confidence or 0.0
        logger.info("legacy_path | intent=%s | confidence=%.2f", intent, confidence)

        entities = extract_entities(user_message, intent)

        if intent == "greeting":
            return handle_greeting(user_context)
        elif intent == "faq_query":
            return handle_faq_query(user_message, entities)
        elif intent == "event_query":
            return handle_event_query(user_message, entities)
        elif intent == "donation_request":
            return handle_donation(entities)
        elif intent == "directions_request":
            return handle_directions(user_message, entities)
        else:
            return handle_unknown(user_message)

    except Exception as exc:
        logger.exception("Error in build_response: %s", exc)
        return "I'm experiencing technical difficulties. Please try again or contact the temple at (469) 606-3119."


if __name__ == "__main__":
    test_messages = [
        "Hello",
        "Where is the temple?",
        "What time is Friday satsang?",
        "How do I donate?",
        "Directions from Dallas",
        "What's the weather?",
    ]

    print("\n=== Response Builder Test ===\n")
    for message in test_messages:
        print(f"USER: {message}")
        print(f"BOT: {build_response(message)}")
        print("\n" + "=" * 50 + "\n")
